# This file was generated by GoReleaser. DO NOT EDIT.
cask "cswap" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "00229c34ce9242d4cfa8cac0d3298b45dfcffeb573b7b6f6e4b0f713b37b8d50"
      url "https://github.com/blairham/go-claude-swap/releases/download/v#{version}/cswap_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "de7dc79ff5bb0a01faa5a4e04e16e343b88b8b2087407734162190bb06038f65"
      url "https://github.com/blairham/go-claude-swap/releases/download/v#{version}/cswap_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8db9be9f3883fb59d420a065c9d10471c44ab0aad2c8ffa30db5604b94c3568a"
      url "https://github.com/blairham/go-claude-swap/releases/download/v#{version}/cswap_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9545931cc8467d3094b6f47a0bf7db6c8df39a0b695f934008d4618023200031"
      url "https://github.com/blairham/go-claude-swap/releases/download/v#{version}/cswap_Linux_arm64.tar.gz"
    end
  end

  name "cswap"
  desc "Multi-account manager for Claude Code (Go rewrite of claude-swap)"
  homepage "https://github.com/blairham/go-claude-swap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cswap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cswap"]
      if system_command("/usr/bin/codesign", args: ["-v", "#{staged_path}/cswap"]).exit_status != 0
        system_command "/usr/bin/codesign", args: ["--force", "--sign", "-", "#{staged_path}/cswap"]
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The auto-switch service is managed by cswap itself, not by `brew services`:

      cswap service install    # launchd (macOS) / systemd --user (Linux)
      cswap service status
  EOS
end
