# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghorg" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "fe442e3cf22ec80e11d54e8a1a2d25499f49a14ee3855d4c54bae31a9afb49e5"
      url "https://github.com/blairham/ghorg/releases/download/v#{version}/ghorg_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0c52a6f1c9d707ffaf12cb842203c5793434b7a1237f23e0104a2dd646adb589"
      url "https://github.com/blairham/ghorg/releases/download/v#{version}/ghorg_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9a2a8fc051cc3531eac759ff536b87dceee7f05ec7f39e61e83c94a1fb5ee62c"
      url "https://github.com/blairham/ghorg/releases/download/v#{version}/ghorg_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "027cac32c4edad675f7d2219a41b31561865b9b73d78d7bf77e60776b07e3f58"
      url "https://github.com/blairham/ghorg/releases/download/v#{version}/ghorg_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "ghorg"
  desc "Quickly clone an entire org/users repositories into one directory"
  homepage "https://github.com/blairham/ghorg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghorg"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghorg"]
      if system_command("/usr/bin/codesign", args: ["-v", "#{staged_path}/ghorg"]).exit_status != 0
        system_command "/usr/bin/codesign", args: ["--force", "--sign", "-", "#{staged_path}/ghorg"]
      end
    end
  end

  # No zap stanza required

end
