# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghorg" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "e9f61be82e8d96fa6104ac9dea35633e85074a830acde948e6c6d9c98d5e4b14"
      url "https://github.com/blairham/ghorg/releases/download/v#{version}/ghorg_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e2674bc9e17dd219f2d113e79ecd20723bc1aaa6814a57f7dd509cc31a38fd4c"
      url "https://github.com/blairham/ghorg/releases/download/v#{version}/ghorg_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "90fd27d1d4c924aad61592bdf6b644e368afee2c0d60c2ac1a90a061c0fc29b1"
      url "https://github.com/blairham/ghorg/releases/download/v#{version}/ghorg_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6e57add5366d27b7a799063bca110cd127609a67867fcacf320fa9a9f480d117"
      url "https://github.com/blairham/ghorg/releases/download/v#{version}/ghorg_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "ghorg"
  desc "Quickly clone an entire org/users repositories into one directory"
  homepage "https://github.com/blairham/ghorg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghorg"

  # No zap stanza required

end
