# This file was generated by GoReleaser. DO NOT EDIT.
cask "pre-commit" do
  version "4.6.2"

  on_macos do
    on_intel do
      sha256 "cbf25ae0ed1f12276bd0cc40b8bfba141a65ddc2cf09a7e6431cad5490cbd15f"
      url "https://github.com/blairham/go-pre-commit/releases/download/v#{version}/pre-commit_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3b30925b6b4e49b467435651ede14883abad389731ac12c9d1a498b78f8f57fc"
      url "https://github.com/blairham/go-pre-commit/releases/download/v#{version}/pre-commit_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef7fbac3692efe0cc6ec5e0bf52a55a6bc85a5e7c29054da5273d5ec624260bc"
      url "https://github.com/blairham/go-pre-commit/releases/download/v#{version}/pre-commit_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6bbaf2b4dcb91ee443f644e20089c92ce58ff6de14841343d0c05fa7d5f04025"
      url "https://github.com/blairham/go-pre-commit/releases/download/v#{version}/pre-commit_Linux_arm64.tar.gz"
    end
  end

  name "pre-commit"
  desc "A fast Go reimplementation of pre-commit"
  homepage "https://github.com/blairham/go-pre-commit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pre-commit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pre-commit"]
      if system_command("/usr/bin/codesign", args: ["-v", "#{staged_path}/pre-commit"]).exit_status != 0
        system_command "/usr/bin/codesign", args: ["--force", "--sign", "-", "#{staged_path}/pre-commit"]
      end
    end
  end

  # No zap stanza required

end
