# This file was generated by GoReleaser. DO NOT EDIT.
cask "pre-commit" do
  version "4.6.0"

  on_macos do
    on_intel do
      sha256 "5b105b29904858d51aa8cd3e9464c4974499bc3d9e6a5b82bff9c363b7e32c3a"
      url "https://github.com/blairham/go-pre-commit/releases/download/v#{version}/pre-commit_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b475b557be5e007879463638270fce52618ed96dfa7e41ba0495c185f91333eb"
      url "https://github.com/blairham/go-pre-commit/releases/download/v#{version}/pre-commit_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4a7c23177ef293dddc178f4fcf7e65a189fabd0f9719deded9ec5d9f7f318ba2"
      url "https://github.com/blairham/go-pre-commit/releases/download/v#{version}/pre-commit_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7b96b3d74b6435f82380b5086271faeffb076249b794e6a713f8639d83a6b1c0"
      url "https://github.com/blairham/go-pre-commit/releases/download/v#{version}/pre-commit_Linux_arm64.tar.gz"
    end
  end

  name "pre-commit"
  desc "A fast Go reimplementation of pre-commit"
  homepage "https://github.com/blairham/go-pre-commit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pre-commit"

  # No zap stanza required

end
