# This file was generated by GoReleaser. DO NOT EDIT.
cask "pre-commit" do
  version "0.0.0"

  on_macos do
    on_intel do
      url "https://github.com/blairham/go-pre-commit/releases/download/v#{version}/pre-commit_Darwin_x86_64.tar.gz"
      sha256 "b14a47a6b05156ee8c502c9e91e2bd81fa191dc6af198d4f410477dcbea45031"
    end
    on_arm do
      url "https://github.com/blairham/go-pre-commit/releases/download/v#{version}/pre-commit_Darwin_arm64.tar.gz"
      sha256 "b85a413d5ace1f081da08c746a4981e57d72e1af27c45bed522788f7b7406d23"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/blairham/go-pre-commit/releases/download/v#{version}/pre-commit_Linux_x86_64.tar.gz"
      sha256 "47164f83fd19bcfb07865c9b95c4a1e67f9d4df625e0dbcb91c2996dbc260ea7"
    end
    on_arm do
      url "https://github.com/blairham/go-pre-commit/releases/download/v#{version}/pre-commit_Linux_arm64.tar.gz"
      sha256 "cd0ec700c052e15514924a5172fd91cf590695daecf043e4e786cbf6ebfa0a64"
    end
  end

  name "pre-commit"
  desc "A fast Go reimplementation of pre-commit"
  homepage "https://github.com/blairham/go-pre-commit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pre-commit"

  # No zap stanza required

end
