# This file was generated by GoReleaser. DO NOT EDIT.
cask "stevedore" do
  version "0.0.8"

  on_macos do
    on_intel do
      sha256 "2ac637ea06a245fdaee6e3d3dc7853db248805daac6b79bf904f99f7131f609c"
      url "https://github.com/blairham/stevedore/releases/download/v#{version}/stevedore_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "44e93fcc2f6ec085cce8a8c28685677431b0c173a56c3781a39275c26b1a13ad"
      url "https://github.com/blairham/stevedore/releases/download/v#{version}/stevedore_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ce55b723aa6a3c93c635f2c7433cb0176917f7ca9856bc82b19835456f7f14a2"
      url "https://github.com/blairham/stevedore/releases/download/v#{version}/stevedore_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d53838136823c697773c69c05d599d4c4066085fdb6176f97dbb0b51f9d54162"
      url "https://github.com/blairham/stevedore/releases/download/v#{version}/stevedore_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "stevedore"
  desc "Release Docker/OCI images the way goreleaser releases binaries"
  homepage "https://github.com/blairham/stevedore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stevedore"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stevedore"]
      if system_command("/usr/bin/codesign", args: ["-v", "#{staged_path}/stevedore"]).exit_status != 0
        system_command "/usr/bin/codesign", args: ["--force", "--sign", "-", "#{staged_path}/stevedore"]
      end
    end
  end

  # No zap stanza required

end
