# This file was generated by GoReleaser. DO NOT EDIT.
cask "stevedore" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "b41326a4d6b20200e3c51182cd8d9f9477392f77315d0c5a51cb337618937d4f"
      url "https://github.com/blairham/stevedore/releases/download/v#{version}/stevedore_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4869695846e12940cda911bda520ee35a57d30a130f8d6eeab119c19454135a2"
      url "https://github.com/blairham/stevedore/releases/download/v#{version}/stevedore_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ff85b7c2610da2fd96638d9b40e463005baa7c8b80f64159dec910fc761ed87f"
      url "https://github.com/blairham/stevedore/releases/download/v#{version}/stevedore_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "92c8322f627f2ddb833a054b07960d06796d3c25a2023d6fef91bd58de54701e"
      url "https://github.com/blairham/stevedore/releases/download/v#{version}/stevedore_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "stevedore"
  desc "Release Docker/OCI images the way goreleaser releases binaries"
  homepage "https://github.com/blairham/stevedore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stevedore"

  # No zap stanza required

end
