# This file was generated by GoReleaser. DO NOT EDIT.
cask "stevedore" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "3ac6b8697c93cb296836dc808130154d67b5e3169cda3819f57c5fbca1b5b002"
      url "https://github.com/blairham/stevedore/releases/download/v#{version}/stevedore_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8908f6d21cc8117a5b0a941d6d432ccc25408e4e7c6e50db3db08c20ab28ebbc"
      url "https://github.com/blairham/stevedore/releases/download/v#{version}/stevedore_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "43d16ff8cf881eebede46c6b098a9e4ce68511851172aaaa904663a653e05186"
      url "https://github.com/blairham/stevedore/releases/download/v#{version}/stevedore_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5c3a9a55b84d4818807479e9bf633ebbca124df78463049083b9ef6b5d08e507"
      url "https://github.com/blairham/stevedore/releases/download/v#{version}/stevedore_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "stevedore"
  desc "Release Docker/OCI images the way goreleaser releases binaries"
  homepage "https://github.com/blairham/stevedore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stevedore"

  # No zap stanza required

end
