# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cswap < Formula
  desc "Multi-account manager for Claude Code (Go rewrite of claude-swap)"
  homepage "https://github.com/blairham/go-claude-swap"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/go-claude-swap/releases/download/v0.2.0/cswap_Darwin_x86_64.tar.gz"
      sha256 "68f2cc888b0f5b7a1d7abc847817697e089112aaba2ad44048b8a58a8cf89060"

      define_method(:install) do
        bin.install "cswap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/go-claude-swap/releases/download/v0.2.0/cswap_Darwin_arm64.tar.gz"
      sha256 "083f1485a8a85566ebe56a8db007acf0c9496290a319534acf29fa048f864e32"

      define_method(:install) do
        bin.install "cswap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/go-claude-swap/releases/download/v0.2.0/cswap_Linux_x86_64.tar.gz"
      sha256 "7b45745408c683a466678ffd0af381691833a16fcf186847c72c25cf653aa4e8"
      define_method(:install) do
        bin.install "cswap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/go-claude-swap/releases/download/v0.2.0/cswap_Linux_arm64.tar.gz"
      sha256 "cdb2aa23d7f92cb158f10a210130ed38c79a14050f8ff2b50b58d514b3e40270"
      define_method(:install) do
        bin.install "cswap"
      end
    end
  end

  service do
    run [opt_bin/"cswap", "auto"]
    keep_alive true
    log_path var/"log/cswap-auto.log"
    error_log_path var/"log/cswap-auto.log"
  end

  test do
    system "#{bin}/cswap", "--version"
  end
end
