# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cswap < Formula
  desc "Multi-account manager for Claude Code (Go rewrite of claude-swap)"
  homepage "https://github.com/blairham/go-claude-swap"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/go-claude-swap/releases/download/v0.3.0/cswap_Darwin_x86_64.tar.gz"
      sha256 "974f7e94522f77dae87f0ad09085988ebb795ee7a1fb90fe6c2936962688c4dd"

      define_method(:install) do
        bin.install "cswap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/go-claude-swap/releases/download/v0.3.0/cswap_Darwin_arm64.tar.gz"
      sha256 "fcc62ed1aea5b13a000fdb3619ba41526a142d579197103717b46fa0ae8184e4"

      define_method(:install) do
        bin.install "cswap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/go-claude-swap/releases/download/v0.3.0/cswap_Linux_x86_64.tar.gz"
      sha256 "dbf847642185f80bea0d050ebb23ca756b2bfeec45eb6d39a59d84f3e5f212cf"
      define_method(:install) do
        bin.install "cswap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/go-claude-swap/releases/download/v0.3.0/cswap_Linux_arm64.tar.gz"
      sha256 "d9edc0e978e3bb24e99f0bdef38d27cc77e3702adc3fb940140f861bd8223c70"
      define_method(:install) do
        bin.install "cswap"
      end
    end
  end

  service do
    run [opt_bin/"cswap", "auto"]
    keep_alive true
    log_path var/"log/cswap-auto.log"
    error_log_path var/"log/cswap-auto.log"
  end

  test do
    system "#{bin}/cswap", "--version"
  end
end
