# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cswap < Formula
  desc "Multi-account manager for Claude Code (Go rewrite of claude-swap)"
  homepage "https://github.com/blairham/go-claude-swap"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/go-claude-swap/releases/download/v0.1.1/cswap_Darwin_x86_64.tar.gz"
      sha256 "439effaabd44a2f4d1eed0df160ed3e57d4f635d88eb99e2fb3a05be7fca16bd"

      define_method(:install) do
        bin.install "cswap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/go-claude-swap/releases/download/v0.1.1/cswap_Darwin_arm64.tar.gz"
      sha256 "37c9510af6f8266328ca66b891cb7be6312073028c26a6fd52783521e89bee49"

      define_method(:install) do
        bin.install "cswap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/go-claude-swap/releases/download/v0.1.1/cswap_Linux_x86_64.tar.gz"
      sha256 "4d20333e4b7f7a88b4c71786d0ffc4ad32bc020cc8b3ad2aea85e8b6c6f5488b"
      define_method(:install) do
        bin.install "cswap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/go-claude-swap/releases/download/v0.1.1/cswap_Linux_arm64.tar.gz"
      sha256 "572e9dfcf123e1d5798b257cb0529e4625ae2d5f03990b8d5c934e3288ab8aa0"
      define_method(:install) do
        bin.install "cswap"
      end
    end
  end

  service do
    run [opt_bin/"cswap", "auto"]
    keep_alive true
    log_path var/"log/cswap-auto.log"
    error_log_path var/"log/cswap-auto.log"
  end

  test do
    system "#{bin}/cswap", "--version"
  end
end
