# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockmaster < Formula
  desc "k9s-style terminal UI for Docker"
  homepage "https://github.com/blairham/dockmaster"
  version "0.0.16"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/dockmaster/releases/download/v0.0.16/dockmaster_Darwin_x86_64.tar.gz"
      sha256 "6d45081195270214606ec35dbddebd54fd6f99c93b395c2bcd9a570ef3e6162d"

      define_method(:install) do
        bin.install "dockmaster"
        bin.install_symlink "dockmaster" => "dm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/dockmaster/releases/download/v0.0.16/dockmaster_Darwin_arm64.tar.gz"
      sha256 "8b7390915018dec2d770be869692fe0ac916765cdde06d99387aa316bc66b2e8"

      define_method(:install) do
        bin.install "dockmaster"
        bin.install_symlink "dockmaster" => "dm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/dockmaster/releases/download/v0.0.16/dockmaster_Linux_x86_64.tar.gz"
      sha256 "9cb382c8286ce17e62b0789a7203dbf2749523f1867ea10e8a32af4c79354567"
      define_method(:install) do
        bin.install "dockmaster"
        bin.install_symlink "dockmaster" => "dm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/dockmaster/releases/download/v0.0.16/dockmaster_Linux_arm64.tar.gz"
      sha256 "b334b2c026c6dfae9bd3f42ceaaa47a6c3745ac9e930c418797f9eae31a29471"
      define_method(:install) do
        bin.install "dockmaster"
        bin.install_symlink "dockmaster" => "dm"
      end
    end
  end

  test do
    system "#{bin}/dockmaster", "--version"
  end
end
