# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockmaster < Formula
  desc "k9s-style terminal UI for Docker"
  homepage "https://github.com/blairham/dockmaster"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/dockmaster/releases/download/v0.0.1/dockmaster_Darwin_x86_64.tar.gz"
      sha256 "49130ac51d401f1e7e9b7eda198a8300e781f84d71b906b6db0ddf5121ea7b3a"

      define_method(:install) do
        bin.install "dockmaster"
        bin.install_symlink "dockmaster" => "dm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/dockmaster/releases/download/v0.0.1/dockmaster_Darwin_arm64.tar.gz"
      sha256 "f678f235242fb9f00521fe73d61da954396736b7fd81b9feab7ee990fc209b37"

      define_method(:install) do
        bin.install "dockmaster"
        bin.install_symlink "dockmaster" => "dm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/dockmaster/releases/download/v0.0.1/dockmaster_Linux_x86_64.tar.gz"
      sha256 "93de6f5b834ada1c2da9666af56afe1056a778393a890a1f024c01d1cd7b6968"
      define_method(:install) do
        bin.install "dockmaster"
        bin.install_symlink "dockmaster" => "dm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/dockmaster/releases/download/v0.0.1/dockmaster_Linux_arm64.tar.gz"
      sha256 "902758fdebfe16b412ab90fba7ec66d12e338706ebec0262cff2296aaa0f5f88"
      define_method(:install) do
        bin.install "dockmaster"
        bin.install_symlink "dockmaster" => "dm"
      end
    end
  end

  test do
    system "#{bin}/dockmaster", "--version"
  end
end
