# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockmaster < Formula
  desc "k9s-style terminal UI for Docker"
  homepage "https://github.com/blairham/dockmaster"
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/dockmaster/releases/download/v0.0.3/dockmaster_Darwin_x86_64.tar.gz"
      sha256 "4176aac695c642237e549b4ab2d341032ce20a5e34acd13dec1c2cc6a3b3bcad"

      define_method(:install) do
        bin.install "dockmaster"
        bin.install_symlink "dockmaster" => "dm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/dockmaster/releases/download/v0.0.3/dockmaster_Darwin_arm64.tar.gz"
      sha256 "fa6bcadcbca1e51fdb9d6b69cffd807c1d38e55c60c83ad1e862bf575ed0a991"

      define_method(:install) do
        bin.install "dockmaster"
        bin.install_symlink "dockmaster" => "dm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/dockmaster/releases/download/v0.0.3/dockmaster_Linux_x86_64.tar.gz"
      sha256 "a9763f5304a08c0daf8dfc24724166792bddd49cc4b46fb193591d084437f0e6"
      define_method(:install) do
        bin.install "dockmaster"
        bin.install_symlink "dockmaster" => "dm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/dockmaster/releases/download/v0.0.3/dockmaster_Linux_arm64.tar.gz"
      sha256 "0b9917628e8522419b813ebd2096d83ce55672282388f75b8cd1768abb0b2493"
      define_method(:install) do
        bin.install "dockmaster"
        bin.install_symlink "dockmaster" => "dm"
      end
    end
  end

  test do
    system "#{bin}/dockmaster", "--version"
  end
end
