# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghorg < Formula
  desc "Quickly clone an entire org/users repositories into one directory"
  homepage "https://github.com/blairham/ghorg"
  version "0.1.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/ghorg/releases/download/v0.1.5/ghorg_0.1.5_Darwin_x86_64.tar.gz"
      sha256 "30aa56af5969bfcdf85ea7d69814eb33056eab65af10d3ae15f541989aa3dd5b"

      define_method(:install) do
        bin.install "ghorg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/ghorg/releases/download/v0.1.5/ghorg_0.1.5_Darwin_arm64.tar.gz"
      sha256 "020ee4e8c0fac792e9384e7892793c737b06c891dd9f284213161f51da3be099"

      define_method(:install) do
        bin.install "ghorg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/ghorg/releases/download/v0.1.5/ghorg_0.1.5_Linux_x86_64.tar.gz"
      sha256 "47795ba34627eadeca9bcb0647f7cdbdfcc0820e3bb487b2fc25d3c680307038"
      define_method(:install) do
        bin.install "ghorg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/ghorg/releases/download/v0.1.5/ghorg_0.1.5_Linux_arm64.tar.gz"
      sha256 "02a14377e1fc92cc4a6f514318e0fa360cf74b7bebccf1adda51f491a2abf4fc"
      define_method(:install) do
        bin.install "ghorg"
      end
    end
  end

  test do
    system "#{bin}/ghorg", "version"
  end
end
