# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghorg < Formula
  desc "Quickly clone an entire org/users repositories into one directory"
  homepage "https://github.com/blairham/ghorg"
  version "0.1.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/ghorg/releases/download/v0.1.6/ghorg_0.1.6_Darwin_x86_64.tar.gz"
      sha256 "0c8db736b95335d255a2bf109ac362fe31c2461d5289f82ef6ebd1e87c5eddc1"

      define_method(:install) do
        bin.install "ghorg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/ghorg/releases/download/v0.1.6/ghorg_0.1.6_Darwin_arm64.tar.gz"
      sha256 "9d3b6e21610a6e10447bdb2f77265c299110ea998ac283d3b2eb761de25ccf9b"

      define_method(:install) do
        bin.install "ghorg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/ghorg/releases/download/v0.1.6/ghorg_0.1.6_Linux_x86_64.tar.gz"
      sha256 "d26e0076bf0b8b148136ec385ce15f3e150a1f879a237e55a13b8809f3a4963e"
      define_method(:install) do
        bin.install "ghorg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/ghorg/releases/download/v0.1.6/ghorg_0.1.6_Linux_arm64.tar.gz"
      sha256 "c1f4d7192b0994cb0adc289b4a912529fb7bd41bfd22b04ec7364ffff9cd8d54"
      define_method(:install) do
        bin.install "ghorg"
      end
    end
  end

  test do
    system "#{bin}/ghorg", "version"
  end
end
