# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gish < Formula
  desc "Interactive shell: zsh ergonomics, bash compatibility, gRPC-native plugins"
  homepage "https://github.com/blairham/gish"
  version "0.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/gish/releases/download/v0.0.0/gish_Darwin_x86_64.tar.gz"
      sha256 "99b075cfca4b562ae14c81e0e6900c402cee35c2805fee9ed58f37a58bb0b2c6"

      define_method(:install) do
        bin.install "gish"
        bin.install "gish-git"
        bin.install "gish-carapace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/gish/releases/download/v0.0.0/gish_Darwin_arm64.tar.gz"
      sha256 "1a052d851415bd534b40e98c3a1add229f1aff14e1235846f1ef09da5918a619"

      define_method(:install) do
        bin.install "gish"
        bin.install "gish-git"
        bin.install "gish-carapace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/gish/releases/download/v0.0.0/gish_Linux_x86_64.tar.gz"
      sha256 "854dbca1dae9f70f33d8b36facc537616d2d0733d03da38c67eb4a9242f462c6"
      define_method(:install) do
        bin.install "gish"
        bin.install "gish-git"
        bin.install "gish-carapace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/gish/releases/download/v0.0.0/gish_Linux_arm64.tar.gz"
      sha256 "0aefbb1f4c1a76839f9cc897fd336934bfc1d37d6f20f49b20843ad5254f54a7"
      define_method(:install) do
        bin.install "gish"
        bin.install "gish-git"
        bin.install "gish-carapace"
      end
    end
  end

  def caveats
    <<~EOS
      To use gish as your login shell:
        echo "#{opt_bin}/gish" | sudo tee -a /etc/shells
        chsh -s "#{opt_bin}/gish"

      The bundled tier-2 plugins activate once linked into the plugin dir:
        mkdir -p "${XDG_DATA_HOME:-$HOME/.local/share}/gish/plugins"
        ln -sf "#{opt_bin}/gish-git" "#{opt_bin}/gish-carapace" "${XDG_DATA_HOME:-$HOME/.local/share}/gish/plugins/"
    EOS
  end

  test do
    system "#{bin}/gish", "--version"
  end
end
