# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K4a < Formula
  desc "Terminal UI for Kafka clusters, in the style of k9s"
  homepage "https://github.com/blairham/k4a"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/k4a/releases/download/v0.0.1/k4a_Darwin_x86_64.tar.gz"
      sha256 "1461214a735bc28b4319488ae90c301fad2e455b8a36466fbca2da983de36dfe"

      define_method(:install) do
        bin.install "k4a"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/k4a/releases/download/v0.0.1/k4a_Darwin_arm64.tar.gz"
      sha256 "80d0f532bf5075a3393a886df26f7f645771f6daf8148f8dda4f45700ec65078"

      define_method(:install) do
        bin.install "k4a"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/k4a/releases/download/v0.0.1/k4a_Linux_x86_64.tar.gz"
      sha256 "06880dbb5597539d79478f3a73bace8065cdec1549aa92a7ea77b991663666fd"
      define_method(:install) do
        bin.install "k4a"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/k4a/releases/download/v0.0.1/k4a_Linux_arm64.tar.gz"
      sha256 "83e175bdf886de7295495f5c03a08f3ac573924d47067c50183a030717b8c4be"
      define_method(:install) do
        bin.install "k4a"
      end
    end
  end

  test do
    system "#{bin}/k4a", "version"
  end
end
