# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K4a < Formula
  desc "Terminal UI for Kafka clusters, in the style of k9s"
  homepage "https://github.com/blairham/k4a"
  version "0.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/k4a/releases/download/v0.0.0/k4a_Darwin_x86_64.tar.gz"
      sha256 "d426ab0ffcc2c1553d316fd5f78e89e0bb9112eab3028075bf8dbe031866e102"

      define_method(:install) do
        bin.install "k4a"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/k4a/releases/download/v0.0.0/k4a_Darwin_arm64.tar.gz"
      sha256 "2b28a7d4098773c77fba187d8b6084ace57123862d176a607b82e05e456abcea"

      define_method(:install) do
        bin.install "k4a"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/k4a/releases/download/v0.0.0/k4a_Linux_x86_64.tar.gz"
      sha256 "28656f7b3a894474aa1bfaa34dc3a3f796ed3f4f79c943e180c29cfefe72e78a"
      define_method(:install) do
        bin.install "k4a"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/k4a/releases/download/v0.0.0/k4a_Linux_arm64.tar.gz"
      sha256 "d45c9cb936912b035d93f4e0a35a289cef35a21b68b69cab8a5e4944f427e658"
      define_method(:install) do
        bin.install "k4a"
      end
    end
  end

  test do
    system "#{bin}/k4a", "version"
  end
end
