# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PreCommit < Formula
  desc "A fast Go reimplementation of pre-commit"
  homepage "https://github.com/blairham/go-pre-commit"
  version "4.6.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/go-pre-commit/releases/download/v4.6.4/pre-commit_Darwin_x86_64.tar.gz"
      sha256 "f37a30318a2d27cadece3e61f191498205a4209d71443b1f18c3339cf8ce91f3"

      define_method(:install) do
        bin.install "pre-commit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/go-pre-commit/releases/download/v4.6.4/pre-commit_Darwin_arm64.tar.gz"
      sha256 "37f1570662196afe93a64c0a4a6b270dc573b6f62e98061b808daed5afaf3c78"

      define_method(:install) do
        bin.install "pre-commit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/go-pre-commit/releases/download/v4.6.4/pre-commit_Linux_x86_64.tar.gz"
      sha256 "08c2d54004018963e2aaebe4bd79534c273cf9d4ca255de652ecdd2df1c2a443"
      define_method(:install) do
        bin.install "pre-commit"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/go-pre-commit/releases/download/v4.6.4/pre-commit_Linux_armv6.tar.gz"
      sha256 "bd91235f25c0e6d18d6d8635749e979fe9e5be9a31af8bdee3f6687ae972b47a"
      define_method(:install) do
        bin.install "pre-commit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/go-pre-commit/releases/download/v4.6.4/pre-commit_Linux_arm64.tar.gz"
      sha256 "7bb8b923a2f9d31a30333b0510df5258b950f3eda6dcaa236981b9f9d12ee1da"
      define_method(:install) do
        bin.install "pre-commit"
      end
    end
  end

  test do
    system "#{bin}/pre-commit", "--version"
  end
end
