# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sh < Formula
  desc "A shell parser and interpreter in Go, with bash, zsh, ksh, dash and ash dialects"
  homepage "https://github.com/blairham/sh"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/sh/releases/download/v0.0.1/sh_Darwin_x86_64.tar.gz"
      sha256 "bd80e641b6f3ae2b95781d01f3b45ee9811aa6c75f9d0607bcc3e477b0dfdade"

      define_method(:install) do
        # Every binary in the archive, `ash` included. An explicit list is what
        # dropped it once already: the archive carries all six, and
        # `libexec.install` silently skips the name it was not given, so the keg
        # came out missing a shell the caveats below promise by name.
        libexec.install "sh", "bash", "zsh", "ksh", "dash", "ash"
        # Not into libexec beside the binaries. The function search is
        # `<prefix>/share/sh/site-functions` then `<prefix>/share/sh/functions`,
        # and the prefix a binary in the keg's libexec derives is the keg — so
        # this is the directory the shell will actually look in, and
        # `share/sh/site-functions` is left for whatever a person installs later.
        (share/"sh").install "share/sh/functions"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/sh/releases/download/v0.0.1/sh_Darwin_arm64.tar.gz"
      sha256 "db9ee9ead983b45a5f8637b38ee709260110bf2228e1cff067988c42c45f6265"

      define_method(:install) do
        # Every binary in the archive, `ash` included. An explicit list is what
        # dropped it once already: the archive carries all six, and
        # `libexec.install` silently skips the name it was not given, so the keg
        # came out missing a shell the caveats below promise by name.
        libexec.install "sh", "bash", "zsh", "ksh", "dash", "ash"
        # Not into libexec beside the binaries. The function search is
        # `<prefix>/share/sh/site-functions` then `<prefix>/share/sh/functions`,
        # and the prefix a binary in the keg's libexec derives is the keg — so
        # this is the directory the shell will actually look in, and
        # `share/sh/site-functions` is left for whatever a person installs later.
        (share/"sh").install "share/sh/functions"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/sh/releases/download/v0.0.1/sh_Linux_x86_64.tar.gz"
      sha256 "5c75cf61f1e0ada90834efdfa3dddf7e478758104cd4224a0de8ade2befbe8a8"
      define_method(:install) do
        # Every binary in the archive, `ash` included. An explicit list is what
        # dropped it once already: the archive carries all six, and
        # `libexec.install` silently skips the name it was not given, so the keg
        # came out missing a shell the caveats below promise by name.
        libexec.install "sh", "bash", "zsh", "ksh", "dash", "ash"
        # Not into libexec beside the binaries. The function search is
        # `<prefix>/share/sh/site-functions` then `<prefix>/share/sh/functions`,
        # and the prefix a binary in the keg's libexec derives is the keg — so
        # this is the directory the shell will actually look in, and
        # `share/sh/site-functions` is left for whatever a person installs later.
        (share/"sh").install "share/sh/functions"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/sh/releases/download/v0.0.1/sh_Linux_arm64.tar.gz"
      sha256 "59ad9000a9dd6cb75a7bf25994f7e38032cc066c1a6d09b5514a3f058d5a7776"
      define_method(:install) do
        # Every binary in the archive, `ash` included. An explicit list is what
        # dropped it once already: the archive carries all six, and
        # `libexec.install` silently skips the name it was not given, so the keg
        # came out missing a shell the caveats below promise by name.
        libexec.install "sh", "bash", "zsh", "ksh", "dash", "ash"
        # Not into libexec beside the binaries. The function search is
        # `<prefix>/share/sh/site-functions` then `<prefix>/share/sh/functions`,
        # and the prefix a binary in the keg's libexec derives is the keg — so
        # this is the directory the shell will actually look in, and
        # `share/sh/site-functions` is left for whatever a person installs later.
        (share/"sh").install "share/sh/functions"
      end
    end
  end

  def caveats
    <<~EOS
      The binaries are named bash, zsh, ksh, dash, ash and sh, so they are NOT linked
      into #{HOMEBREW_PREFIX}/bin — that would shadow the system shells for
      everything on this machine. They live here instead:

        #{opt_libexec}

      Run one by its full path:

        #{opt_libexec}/bash -i

      A session reads what a real shell of the same name reads, in the same order:
      the profile, the run-commands file, and the machine's own file in front of
      each. To use one as your login shell, add its full path to /etc/shells and
      then chsh to it — read this first, and keep the terminal you ran chsh in
      open until a new window works:

        https://github.com/blairham/sh/blob/main/docs/install.md
    EOS
  end

  test do
    # One row per shipped binary. The list in `install:` above is explicit, so
    # a new dialect is installed only if somebody remembers to add it — these
    # rows are what turns forgetting into a failed release instead of a keg
    # that is quietly missing a shell.
    %w[sh bash zsh ksh dash ash].each do |shell|
      assert_equal "hi", shell_output("#{libexec}/#{shell} -c 'echo hi'").chomp
    end
    # The shipped functions are reachable from the default search, which is
    # the half a missing `files:` entry above would break silently: the shell
    # still starts, and every `autoload` in a real startup file fails at the
    # call instead.
    assert_equal "5.9", shell_output(
      "#{libexec}/zsh -f -c 'autoload -Uz is-at-least; is-at-least 5.0 5.9 && echo 5.9'"
    ).chomp
  end
end
