# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stevedore < Formula
  desc "Release Docker/OCI images the way goreleaser releases binaries"
  homepage "https://github.com/blairham/stevedore"
  version "1.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/stevedore/releases/download/v1.0.6/stevedore_1.0.6_Darwin_x86_64.tar.gz"
      sha256 "557268dcf921fc85fa44a9c2ccc8ab435819641b52f39062651fa3d9cbc2e671"

      define_method(:install) do
        bin.install "stevedore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/stevedore/releases/download/v1.0.6/stevedore_1.0.6_Darwin_arm64.tar.gz"
      sha256 "c64e7631bddd99f51ae62513e89bccab90cf5a1048f2ea101da3a393ce608947"

      define_method(:install) do
        bin.install "stevedore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/stevedore/releases/download/v1.0.6/stevedore_1.0.6_Linux_x86_64.tar.gz"
      sha256 "17650d580ae710e11836e1002902033f79d233582e9b2a169c5268186e7dba41"
      define_method(:install) do
        bin.install "stevedore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/stevedore/releases/download/v1.0.6/stevedore_1.0.6_Linux_arm64.tar.gz"
      sha256 "e9f70480aef640bf5dbe845451121929fa953b9ea80a489810d6026da7494164"
      define_method(:install) do
        bin.install "stevedore"
      end
    end
  end

  test do
    system "#{bin}/stevedore", "--version"
  end
end
