# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stevedore < Formula
  desc "Release Docker/OCI images the way goreleaser releases binaries"
  homepage "https://github.com/blairham/stevedore"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/stevedore/releases/download/v0.0.9/stevedore_0.0.9_Darwin_x86_64.tar.gz"
      sha256 "ae43ccb677670adbc942d8223c6c70e07491333499b2d053e37fc6514522497a"

      define_method(:install) do
        bin.install "stevedore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/stevedore/releases/download/v0.0.9/stevedore_0.0.9_Darwin_arm64.tar.gz"
      sha256 "15a609d0a7e9ac1dabb8d2cf696cfa9955fdc4b224bb84385d971eaf6a5fc399"

      define_method(:install) do
        bin.install "stevedore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/stevedore/releases/download/v0.0.9/stevedore_0.0.9_Linux_x86_64.tar.gz"
      sha256 "3a57562fd3c896cca7d0e4d640e53bc1ac33dfbbf71f3188916c373eda21f9bd"
      define_method(:install) do
        bin.install "stevedore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/stevedore/releases/download/v0.0.9/stevedore_0.0.9_Linux_arm64.tar.gz"
      sha256 "e93972ee8cb881429254ea90c5de34edea39a0a7e3b1198b1687a68f75ecc4b8"
      define_method(:install) do
        bin.install "stevedore"
      end
    end
  end

  test do
    system "#{bin}/stevedore", "--version"
  end
end
