# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stevedore < Formula
  desc "Release Docker/OCI images the way goreleaser releases binaries"
  homepage "https://github.com/blairham/stevedore"
  version "1.0.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/blairham/stevedore/releases/download/v1.0.5/stevedore_1.0.5_Darwin_x86_64.tar.gz"
      sha256 "005a6786d91e94d54292bd8968a7f4a24e872f99a1a5dd23f268b0b0fddc12a3"

      define_method(:install) do
        bin.install "stevedore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/blairham/stevedore/releases/download/v1.0.5/stevedore_1.0.5_Darwin_arm64.tar.gz"
      sha256 "c004bb04ae607976fddd7c9bab60d350b8314b2e891ebc780659258808af62ac"

      define_method(:install) do
        bin.install "stevedore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/stevedore/releases/download/v1.0.5/stevedore_1.0.5_Linux_x86_64.tar.gz"
      sha256 "646f549e0a207d21ba48a9558515dae5bfe6806db80c962ed5ca12340d0b40a5"
      define_method(:install) do
        bin.install "stevedore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/blairham/stevedore/releases/download/v1.0.5/stevedore_1.0.5_Linux_arm64.tar.gz"
      sha256 "87c6b5509b14f916cc558f790e56b9baa8ea0d4757d6b571a19b7fba2b1eaa3c"
      define_method(:install) do
        bin.install "stevedore"
      end
    end
  end

  test do
    system "#{bin}/stevedore", "--version"
  end
end
